" Personal vimrc.
" Plugin manager: vim-plug (https://github.com/junegunn/vim-plug).
" install.sh ensures vim-plug is bootstrapped, then runs :PlugInstall.

set nocompatible

filetype plugin indent on
syntax enable

" ---- core editor behavior ----
set encoding=utf-8
set fileencoding=utf-8
set hidden                    " keep buffers around when switching
set history=1000
set undolevels=1000
set updatetime=300
set ttimeoutlen=10            " quicker reaction to <Esc>

set mouse=a                   " mouse in all modes
set clipboard=unnamed         " yank/paste through system clipboard
set autoread                  " pick up external changes to open files

" no swap / backup noise
set nobackup
set nowritebackup
set noswapfile

" line numbering
set number
set relativenumber

" status / scroll
set laststatus=2
set scrolloff=5
set sidescrolloff=8
set signcolumn=auto

" search
set incsearch
set hlsearch
set ignorecase
set smartcase

" ---- leader ----
let mapleader=","

" handy mappings
nnoremap <silent> <leader><space> :nohlsearch<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" ---- plugins (vim-plug) ----
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'

call plug#end()

" airline / tabline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
